-- MySQL Script generated by MySQL Workbench
-- Tue Feb 27 21:40:22 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema metaranking
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema metaranking
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `metaranking` DEFAULT CHARACTER SET utf8 ;
USE `metaranking` ;

-- -----------------------------------------------------
-- Table `metaranking`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metaranking`.`user` (
  `id` INT NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `metaranking`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metaranking`.`tag` (
  `id` INT NOT NULL,
  `label` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metaranking`.`mood`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metaranking`.`mood` (
  `id` INT NOT NULL,
  `label` VARCHAR(255) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` () VISIBLE,
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `metaranking`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metaranking`.`tag_assoc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metaranking`.`tag_assoc` (
  `id` INT NOT NULL,
  `tag1_id` INT NOT NULL,
  `tag2_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `tag1_id_idx` (`tag1_id` ASC, `tag2_id` ASC) VISIBLE,
  CONSTRAINT `tag1_id`
    FOREIGN KEY (`tag1_id` , `tag2_id`)
    REFERENCES `metaranking`.`tag` (`id` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metaranking`.`vote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metaranking`.`vote` (
  `id` INT NOT NULL,
  `vote_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `tag_assoc_id` INT NOT NULL,
  `mood_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `mood_id_idx` (`mood_id` ASC) VISIBLE,
  INDEX `tag_assoc_id_idx` (`tag_assoc_id` ASC) VISIBLE,
  CONSTRAINT `mood_id`
    FOREIGN KEY (`mood_id`)
    REFERENCES `metaranking`.`mood` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tag_assoc_id`
    FOREIGN KEY (`tag_assoc_id`)
    REFERENCES `metaranking`.`tag_assoc` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
